# Slightly modified test ZSH config
# Set up the prompt
autoload -Uz promptinit
setopt histignorealldups sharehistory
# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
# Use modern completion system
autoload -Uz compinit
compinit
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git*' formats '(%b) '

# Custom device name?
if [ -e "$HOME/.customShellName" ] ; then
	customDeviceName=" %B%F{green}$(cat $HOME/.customShellName)"
else
	if [ -e "/etc/zsh/.customShellName" ] ; then
		customDeviceName=" %B%F{yellow}$(cat /etc/zsh/.customShellName)"
	fi
fi

# Nested or not?
if [ "$shellCount" != "" ] ; then
	export shellCount=$(($shellCount+1))
else
	export shellCount=0
fi

# Via SSH or not?
termType="term"
if [ "$SSH_CLIENT" != "" ] ; then
	termType="sshd"
fi

# Display current screen
if [ "$STY" != "" ] ; then
	screenSupport="%b%F{white}@%B%F{yellow}$STY"
fi

# Use sudo
if [ "$SUDO_USER" ] ; then
	sudoInfo="%B%F{blue}$SUDO_USER%b%F{white}>"
fi

# Use ZSH in screens by default instead
SHELL="$(which zsh)"

# Reconfigure prompt
shellSymbol="#"
if [ "$(whoami)" != "root" ] ; then
	shellSymbol="\$"
fi

PS1="%b%F{white}[%B%F{green}ZSH$screenSupport$customDeviceName%b%F{white}] %B%F{green}%99<...<%~\
%}%F{white}
${sudoInfo}%B%F{cyan}%n%b%F{white}:%B%F{yellow}$termType%b%F{white}-%B%F{yellow}$shellCount %B%F{white}$shellSymbol %b%f%k"
