#!/bin/bash
echo Installing JACK2...
apt install -y jackd2 jackd- qjackctl-
echo Installing Cadence...
apt install -y cadence jackd- qjackctl-
echo Installing Carla...
apt install -y carla carla-vst carla-lv2
echo Installing libraries for running with PipeWire...
apt install -y pipewire-audio-client-libraries
if [ -e "/etc/pipewire/media-session.d/with-jack" ] ; then
	echo Skipping file creation...
else
	echo Creating file for PipeWire...
	touch /etc/pipewire/media-session.d/with-jack
	echo Redirecting JACK2 to PipeWire...
	ldconfig
fi
echo Done.
exit
